const carFromDbExample = [
  {
    uuid: '06161bda-0dd9-44dc-ad73-b1afba71f392',
    generation: 'B6',
    customIds: {
      avby: {
        brandsId: 6,
        modelId: 5810,
        generationId: 4299,
        carId: 100180235,
      },
    },
    year: 2006,
    photos: [
      'bed8800a-d513-4895-8130-97a0cf3c60fa',
      'f3c8bed2-9a54-4d57-8f9a-da483df414f8',
      'c664f78f-4d20-46b6-9492-481473bb30fb',
      'e16f553f-e078-41f2-ab7b-1758082b6052',
      'ee4c91c9-fe3b-4cbe-ae68-dff5ebd9aedb',
      'a16cbd79-0547-4ff6-8268-cd286da0f1a1',
    ],
    mileage_km: '140000',
    data: {
      id: 100180235,
      originalDaysOnSale: 26,
      advertType: 'cars',
      status: 'archived',
      publicStatus: { label: 'Продано', name: 'sold' },
      price: {
        usd: { currency: 'usd', amount: 8000, amountFiat: 8000 },
        byn: { currency: 'byn', amount: 23404, amountFiat: 23404 },
        rub: { currency: 'rub', amount: 650635, amountFiat: 650635.23 },
        eur: { currency: 'eur', amount: 7280, amountFiat: 7280.99 },
      },
      description:
        'цена написана!!! заменено масло , фильтра , ГРМ, помпа, радиаторы ( основной и кондиционера), расширительный бачок, комплект сцепления и маховик, по ходовой все отлично, резина новая r19, есть r17 с 3 новыми покрышками, одна пробита , один хозяин в РБ с 2011 года.установлен газ год назад, съёмный фаркоп. писать сообщения, номер в объявлении не мой',
      exchange: {
        type: 'without_exchange',
        label: 'Обмен не интересует',
        comment: '',
        exchangeAllowed: 'denied',
      },
      version: 11,
      publishedAt: '2021-01-21T10:34:35+0000',
      indexPromo: false,
      top: false,
      highlight: false,
      removeReason: 'sold_avby',
      videoUrl: '',
      videoUrlId: '',
      removedAt: '2021-02-15T17:27:00+0000',
      sellerName: '',
      questionAllowed: false,
      locationName: 'Гродно',
      shortLocationName: 'Гродно',
      properties: [
        { value: 'Audi', id: 335, name: 'brand', fallbackType: 'string' },
        { value: 'A4', id: 336, name: 'model', fallbackType: 'string' },
        { value: 'B6', id: 337, name: 'generation', fallbackType: 'string' },
        { value: '2006', id: 339, name: 'year', fallbackType: 'string' },
        {
          value: '1.8',
          id: 346,
          name: 'engine_capacity',
          fallbackType: 'string',
        },
        {
          value: 'бензин (пропан-бутан)',
          id: 347,
          name: 'engine_type',
          fallbackType: 'string',
        },
        {
          value: 'механика',
          id: 340,
          name: 'transmission_type',
          fallbackType: 'string',
        },
        {
          value: 'B6 (2000 - 2006)',
          id: 338,
          name: 'generation_with_years',
          fallbackType: 'string',
        },
        {
          value: 'светлый',
          id: 353,
          name: 'interior_color',
          fallbackType: 'string',
        },
        {
          value: 'натуральная кожа',
          id: 354,
          name: 'interior_material',
          fallbackType: 'string',
        },
        {
          value: 'кабриолет',
          id: 349,
          name: 'body_type',
          fallbackType: 'string',
        },
        {
          value: 'передний привод',
          id: 350,
          name: 'drive_type',
          fallbackType: 'string',
        },
        { value: 'чёрный', id: 351, name: 'color', fallbackType: 'string' },
        { value: 140000, id: 345, name: 'mileage_km', fallbackType: 'int' },
        {
          value: 'с пробегом',
          id: 348,
          name: 'condition',
          fallbackType: 'string',
        },
        { value: 8000, id: 344, name: 'price_amount_usd', fallbackType: 'int' },
      ],
      publicUrl: 'https://cars.av.by/audi/a4/100180235',
      year: 2006,
      metadata: {
        condition: { id: 2, label: 'с пробегом' },
        brandId: 6,
        brandSlug: 'audi',
        modelId: 5810,
        modelSlug: 'a4',
        generationId: 4299,
        year: 2006,
      },
      foreignIp: false,
    },
    createdAt: '2023-04-30T10:31:15.015Z',
    updatedAt: '2023-04-30T14:11:41.632Z',
    brandUUID: '3015d850-c13a-440c-b3e6-3be5eec87126',
    modelUUID: '7b099ad3-fdab-47e7-b6cb-ef25376fa117',
    brand: {
      uuid: '3015d850-c13a-440c-b3e6-3be5eec87126',
      title: 'audi',
      customIds: { avby: 6 },
      createdAt: '2023-04-27T20:31:29.852Z',
      updatedAt: '2023-04-27T20:31:29.852Z',
    },
    model: {
      uuid: '7b099ad3-fdab-47e7-b6cb-ef25376fa117',
      title: 'a4',
      customIds: { avby: 5810 },
      createdAt: '2023-04-27T20:42:38.957Z',
      updatedAt: '2023-04-27T20:42:38.957Z',
      brandUUID: '3015d850-c13a-440c-b3e6-3be5eec87126',
    },
  },
];

const lastSoldCarFromAvExample = {
  title: {
    brand: 'Skoda',
    model: 'Felicia',
    generation: 'I',
    year: 1994,
    image: 'https://avcdn.av.by/cargeneration/0000/0025/1519.jpeg',
  },
  mediumPrice: {
    priceUsd: 0,
    priceByn: 0,
    minPriceUsd: 0,
    maxPriceUsd: 0,
    advertCount: 0,
    mainFilter: {
      advertType: 'cars',
      filterType: 'main',
      initialValue:
        'brands[0][brand]=1126&brands[0][generation]=2245&brands[0][model]=1132&condition[0]=2&price_currency=2&year[max]=1994&year[min]=1994',
      url: 'https://cars.av.by/filter?brands[0][brand]=1126&brands[0][model]=1132&brands[0][generation]=2245&year[min]=1994&year[max]=1994&condition[0]=2',
    },
    statisticFilter: {
      advertType: 'cars',
      filterType: 'price-statistics',
      initialValue: 'brand=1126&generation=2245&model=1132&year=1994',
      url: 'https://av.by/ocenka-avto/skoda_felicia_i-1994-1998_1994',
    },
  },
  advertActivity: {
    last: { new: 0, removed: 0 },
    byMonth: [
      { date: '2022-11-01', new: 0, removed: 0 },
      { date: '2022-12-01', new: 0, removed: 0 },
      { date: '2023-01-01', new: 0, removed: 0 },
      { date: '2023-02-01', new: 0, removed: 0 },
      { date: '2023-03-01', new: 0, removed: 0 },
      { date: '2023-04-01', new: 0, removed: 0 },
    ],
  },
  borderedFilters: {
    next: {
      advertType: 'cars',
      filterType: 'price-statistics',
      initialValue: 'brand=1126&generation=2245&model=1132&year=1995',
      url: 'https://av.by/ocenka-avto/skoda_felicia_i-1994-1998_1995',
      year: 1995,
    },
  },
  lastSoldAdverts: [
    {
      id: 100067877,
      originalDaysOnSale: 30,
      advertType: 'cars',
      status: 'archived',
      publicStatus: { label: 'Продано', name: 'sold' },
      price: {
        usd: { currency: 'usd', amount: 699, amountFiat: 699 },
        byn: { currency: 'byn', amount: 2052, amountFiat: 2052.26 },
        rub: { currency: 'rub', amount: 57072, amountFiat: 57072.33 },
        eur: { currency: 'eur', amount: 633, amountFiat: 633.26 },
      },
      description:
        'Продаётся хороший не дорогой автомобиль 1.3 карбюратор, 1994г. 157000 родной пробег, машина очень мало эксплуатировалась. Новый аккумулятор. Торг. ',
      exchange: {
        type: 'without_exchange',
        label: 'Обмен не интересует',
        comment: '',
        exchangeAllowed: 'denied',
      },
      version: 1,
      publishedAt: '2020-11-05T10:49:34+0000',
      indexPromo: false,
      top: false,
      highlight: false,
      removeReason: 'sold_avby',
      videoUrl: '',
      videoUrlId: '',
      removedAt: '2020-12-04T12:48:47+0000',
      photos: [
        {
          id: 8303382,
          main: false,
          mimeType: 'image/jpeg',
          big: {
            width: 612,
            height: 344,
            url: 'https://avcdn.av.by/advertmedium/0000/0830/3384.jpeg',
          },
          medium: {
            width: 612,
            height: 344,
            url: 'https://avcdn.av.by/advertmedium/0000/0830/3384.jpeg',
          },
          small: {
            width: 612,
            height: 344,
            url: 'https://avcdn.av.by/advertmedium/0000/0830/3384.jpeg',
          },
          extrasmall: {
            width: 612,
            height: 344,
            url: 'https://avcdn.av.by/advertmedium/0000/0830/3384.jpeg',
          },
        },
      ],
      sellerName: '',
      questionAllowed: false,
      locationName: 'Гродно',
      shortLocationName: 'Гродно',
      properties: [
        { value: 'Skoda', id: 113, name: 'brand', fallbackType: 'string' },
        { value: 'Felicia', id: 114, name: 'model', fallbackType: 'string' },
        { value: 'I', id: 115, name: 'generation', fallbackType: 'string' },
        { value: '1994', id: 117, name: 'year', fallbackType: 'string' },
        {
          value: '1.3',
          id: 124,
          name: 'engine_capacity',
          fallbackType: 'string',
        },
        {
          value: 'бензин',
          id: 125,
          name: 'engine_type',
          fallbackType: 'string',
        },
        {
          value: 'механика',
          id: 118,
          name: 'transmission_type',
          fallbackType: 'string',
        },
        {
          value: 'I (1994 - 1998)',
          id: 116,
          name: 'generation_with_years',
          fallbackType: 'string',
        },
        {
          value: 'светлый',
          id: 131,
          name: 'interior_color',
          fallbackType: 'string',
        },
        {
          value: 'ткань',
          id: 132,
          name: 'interior_material',
          fallbackType: 'string',
        },
        { value: true, id: 155, name: 'fog_lights', fallbackType: 'boolean' },
        {
          value: 'хэтчбек 5 дв.',
          id: 127,
          name: 'body_type',
          fallbackType: 'string',
        },
        {
          value: 'передний привод',
          id: 128,
          name: 'drive_type',
          fallbackType: 'string',
        },
        { value: 'синий', id: 129, name: 'color', fallbackType: 'string' },
        { value: 157000, id: 123, name: 'mileage_km', fallbackType: 'int' },
        {
          value: 'с пробегом',
          id: 126,
          name: 'condition',
          fallbackType: 'string',
        },
        { value: 699, id: 122, name: 'price_amount_usd', fallbackType: 'int' },
      ],
      publicUrl: 'https://cars.av.by/skoda/felicia/100067877',
      year: 1994,
      metadata: {
        condition: { id: 2, label: 'с пробегом' },
        brandId: 1126,
        brandSlug: 'skoda',
        modelId: 1132,
        modelSlug: 'felicia',
        generationId: 2245,
        year: 1994,
      },
      foreignIp: false,
    },
  ],
};
